### ISSUE TITLE
Feature Request: Installation & Run

### ISSUE THREAD

**Issue by mazzespazze** [Shadowss/TravianZ#1]
Would be possible to have in the read me an example of how to run the whole project? I'm not really familiar with PHP or any server language. 

Thanks a lot, great job all of you! :D

**Comment by gabrielklein** [comment]
It's quite easy if you know how to administrate a linux website. I installed it in ~10 minutes. It's probably a few weeks or months if you know nothing about linux.... :(

Try to search for "LAMP Stack" knowing that many docs are outdated...

You need:
- A domain name (example: mazzespatte.com).
- A linux "host" (example: kimsufi) - I suggest debian or ubuntu. - A computer at home is fine too if you can reach it from outside.

You will need to know the meaning of:
- Debian or Ubuntu.
- Apache.
- MySql (phpmyadmin)
- SSL certificate or HTTPS. (highly recommanded).

**Comment by 221V** [comment]
no needs apache, with nginx less problem

i can help you with installing
you can ask me in telegram --
@TTaraskin
https://t.me/TTaraskin

**Comment by WolfMaster0** [comment]
Hi anyone who could help me run it on vps thank you

**Comment by 221V** [comment]
> Hi anyone who could help me run it on vps thank you

i can, write me in telegram

**Comment by mazzespazze** [comment]
Yeah @gabrielklein I am familiar with Linux. The issue is that there is no section in this git regarding how to configure this project on a server and having it actually running. 

Can anyone here share some? Once an Ubuntu Server is up and running with nginx, what's the next step?

**Comment by 221V** [comment]
nginx, php-fpm, mariadb

also you can use FileZilla and DBeaver

**Comment by 221V** [comment]
do not forget about php extensions
(change from php7.0 to your 7.2/7.4 etc)

```
sudo apt-get install php7.0-mysql
sudo apt-get install php7.0-mbstring
sudo apt-get install php7.0-zip
sudo apt-get install php7.0-bz2
sudo apt-get install php7.0-gd
```

**Comment by Mikkel112** [comment]
Hi, 
For us that dont really understand all the things going on in the background, could anyone make a step by step guide to have to get these things installed proper and working?
Seen a video on Youtube that mentions the need for php and mysql to work, however for most normal people, saying that doesnt really tell us much. 
A guide would be super appreciated.

**Comment by schneond** [comment]
> Hi, For us that dont really understand all the things going on in the background, could anyone make a step by step guide to have to get these things installed proper and working? Seen a video on Youtube that mentions the need for php and mysql to work, however for most normal people, saying that doesnt really tell us much. A guide would be super appreciated.

Working on it ;-)
