### ISSUE TITLE
Game is not showing maps

### ISSUE THREAD

**Issue by mahdidul** [Shadowss/TravianZ#13]
1. expected behaviour : showing game village's map 
2. incorrect behaviour : not showing anything on Village overview https://prnt.sc/rpl0po
3. the operating system & version : windows 7 64-bit
4. PHP version on the server : PHP 7.4.3
5. MySQL / MariaDB version on the server : 10.4.11-MariaDB - mariadb.org binary distribution

**Comment by 221V** [comment]
maybe you lost images?

maybe you lost part of your nginx/apache config?

**Comment by Farky25** [comment]
Hy, today i try it again and got a same problem. Not showing anything on Village overview

**Comment by Shadowss** [comment]
Cannot replicate !
