### ISSUE TITLE
Troops and Nations

### ISSUE THREAD

**Issue by Didiboo** [Shadowss/TravianZ#14]
Hello,
Digging through the code, I found "traces" of the "Monsters" nation.
Since I use this code locally with friends, I decided to add this nation.
I modified the database by adding the columns in the units table, I created the trainings, the reinforcements, the troops in unidata, the templates that are going well, and change an impressive number of "$ i = 1 ; $ i <= 50; $ i ++ "in" $ i = 1; $ i <= 60; $ i ++ "

Everything works perfectly, until I launch troops.
Indeed, the troops do not decrement the village, and when they return, they are added to those of the village.
I have 10 u51 on the village, I send them (reinforcement, attack, raid, whatever, the result is the same), the movement is ok, on the other hand, I have 10 troops in the village + 10 troops in movement, on their return I find myself with 20 u51.
I searched a lot but there I dry, if someone has an idea or a lead, I am interested.
Best Regards.

**Comment by Shadowss** [comment]
We do not support adding tribes/nature or monsters
