### ISSUE TITLE
Game improvement: resource balancing

### ISSUE THREAD

**Issue by Giulianoberaldo** [Shadowss/TravianZ#15]
Hi everyone.
it is normal to set a very high speed for when using this script.
To balance the game, in these conditions, why not be able to set a cost multiplier for building and troop resources?
In this way, a higher speed would reduce the construction time, but a little more strategy would be needed.
another thisng is make buildig update in 1 click, and remove each building page. As happend on travian kingdom, update direcly from dorf1.php and dorf2.php. or creare an option for enable/disable it.
also , why dont' add more spaces on construction waiting loop? this can be a feature for Tplus, or stand alone. 
it can be "unlock other 4 spaces", or unlock one space each for gold price, (kingdom ispiration)

Implement hero, silver, adventures, will be a great thing and it will change a lot this game. Also include more quest, rewards customisation, Remove hero home and integrate oasi on ambasade?

Thanks you

**Comment by 221V** [comment]
github is open source,
so you can do it, you can upgrade it :)

**Comment by Shadowss** [comment]
Not a bug
