### ISSUE TITLE
Unable to conquer WW Village

### ISSUE THREAD

**Issue by nosweat** [Shadowss/TravianZ#16]
1. Expected: Send Chieftains / Catapults to WW Village => at least destroy buildings & Decrease Loyalty.
2. Incorrect: Send Chieftains / Catapults to WW Village:  Only get resources and does not destroy nor decrease loyalty.  (Sent 3 chieftains in 1 wave).
3. Unix based MacOS 10.15.4
4. PHP Ver: 7.4.2
5. MySQL Server Ver: 5.7.26

**Comment by nosweat** [comment]
OK:Update, it was decreasing loyalty, its just not showing from the battle report.  hmmm how to resolve this, only happens with Natars.

**Comment by nosweat** [comment]
Ok. i resolved the loyalty report.  i will resolve the catapult report next

https://pasteboard.co/J96pgMd.png

**Comment by Shadowss** [comment]
Closed!
