### ISSUE TITLE
Building orders are canceled after the attack in WW village

### ISSUE THREAD

**Issue by snip3r-dev** [Shadowss/TravianZ#17]
1. expected Building orders continue after the attack if the catapults did not hit the target
2. incorrect Building orders are canceled after the attack in WW village
3. MacOS 10.15.4
4. PHP 7.4.2
5. MySQL / 5.7.26

Watch the video  : https://youtu.be/tRC-hoA7O2w

**Comment by snip3r-dev** [comment]
Actually, I don’t know this is bug or like this game.
But I thought it was a bug and I loved to tell you

**Comment by snip3r-dev** [comment]
Only one catapult, construction orders were canceled 

When determining the target of the catapult, if there are building orders for this target, it will be canceled

Even if the attack was with one catapult

**Comment by Shadowss** [comment]
Fixed
