### ISSUE TITLE
404 - flaggen.js

### ISSUE THREAD

**Issue by agentcobra** [Shadowss/TravianZ#18]
Hi,
I've just install it (without documentation, I don't find it)
but I have an 404 error with this file :
https://github.com/Shadowss/TravianZ/blob/21a7ea8858589742bd45bd59b56af27b0c4f3247/index.php#L80

**Comment by AleWiccan** [comment]
Check out https://github.com/Shadowss/TravianZ/pull/19/commits/9d53aa3d7037127ceb088a9a1332093f28955bcf
