### ISSUE TITLE
addusers.php troops

### ISSUE THREAD

**Issue by Nx2UndU** [Shadowss/TravianZ#23]
I just set this clone on a localhost and through the admin panel I was able to add users (Farms) but I didn't like the configuration of the users' villages so i changed it in the gameengine/admin/mods/addusers.php ... but I can't figure out what to change to add randome troops to these villages !! the line in the file is written like this 

                //insert units randomly generate the number of troops
                $q = "UPDATE " . TB_PREFIX . "units SET u".(($tribe-1)*10+1)." = ".rand(100, 2000).", u".(($tribe-1)*10+2)." = ".rand(100, 2400).", u".(($tribe-1)*10+3)." = ".rand(100, 1600).", u".(($tribe-1)*10+4)." = ".rand(100, 1500).", u".(($tribe-1)*10+5)." = " .rand(48, 1700).", u".(($tribe-1)*10+6)." = ".rand(60, 1800)." WHERE vref = '".$wid."'";
                mysqli_query($GLOBALS["link"], $q);

what do I change to make it executable when adding new users ???? I'm not a programmer btw so please use simple terminology thnx

**Comment by Shadowss** [comment]
Farms works fine !
