### ISSUE TITLE
PHP 7.0 only ? or PHP 7.2 or 7.4 possible ?

### ISSUE THREAD

**Issue by agony09** [Shadowss/TravianZ#24]
I have 2 questions please.
1. Does this script only run on PHP 7.0 or also on PHP 7.2 or even 7.4? Has anyone been able to test this extensively?
2. I wanted to ask whether it is planned to develop this script further and to fix any bugs?
I'm looking forward to info. 
Thanks very much

**Comment by greldinard** [comment]
Running fine on PHP 7.4.3

**Comment by agony09** [comment]
ok, thanks a lot for info
