### ISSUE TITLE
install/index.php can't load relative files (js, img, ...)

### ISSUE THREAD

**Issue by greldinard** [Shadowss/TravianZ#25]
1. expected behaviour
Installer working smoothly :)

2. incorrect behaviour
In the console window of the browser there are messages like:

    GEThttp://192.168.50.10/install/img/x.gif       [HTTP/1.1 404 Not Found 270ms]

Such messages occur for all referenced files. After all the installer doesn't create any tables in the db and stops with an error: 
    Error creating wdata. Check configuration or file.

But the config.php in the GameEngine dir seems to be alright...

3. the operating system & version
Ubuntu 20

4. PHP version on the server
7.4.3

5. MySQL / MariaDB version on the server
mysql-server 8.0

So why are the relative paths not resolved? I tried creating symlinks, but I assume there is something to add in the apache or nginx  (tried both) or php config?

Any hint appreciated !

**Comment by greldinard** [comment]
My fault! Typo while setting up the privileges on the db.

**Comment by romancherviakov** [comment]
So @greldinard how did you fixed that? I have the same problem, when Automation.php is trying to be execute from /install/ directory path

**Comment by greldinard** [comment]
As I recall... it was some wrong privileges setting on the database or user. I deleted an recreated the database and the user, then it worked.
