### ISSUE TITLE
Server settings not saving

### ISSUE THREAD

**Issue by Hugow1** [Shadowss/TravianZ#29]
**1. expected behaviour**
In the admin profile you can edit the running server settings. Expected would be saving these on the fly.

**2. incorrect behaviour**
Submitting these does not seem to edit anything.

**3. the operating system & version**
Bitnami LAMP stack.

**4. PHP version on the server**
8.0.14

**5. MySQL / MariaDB version on the server**
MariaDB 10.4.22

**Comment by Exiliord** [comment]
Fix:

`chmod 777 GameEngine/config.php`
