### ISSUE TITLE
French support - Feature

### ISSUE THREAD

**Issue by gabrielklein** [Shadowss/TravianZ#3]
Hello, I've installed the server for my son and his school mates.

As they speak French and have just started learning English, is it possible to have the game in French?

Was this project to translate in french already started?

**Comment by 221V** [comment]
> is it possible to have the game in French?

you can help, can create French translations, yep!

**Comment by Shadowss** [comment]
You can translate english file to french here : https://github.com/Shadowss/TravianZ/blob/master/GameEngine/Lang/en.php
