### ISSUE TITLE
[Fixed] Wall and rally point

### ISSUE THREAD

**Issue by Karolis-IT** [Shadowss/TravianZ#30]
I think this project is dead, but anyway a fix to prevent build a wall and rally point anywhere. Also fix a bug where you have rally point (except spot 16) and you can't send troops

![tr](https://user-images.githubusercontent.com/74043471/150024723-0840fbe2-ff27-44f8-83cb-08315d71cb42.png)

**Comment by Qussayyon** [comment]
Hi there,
how to get your code which you corrected the issues?

**Comment by ProphetDK** [comment]
> Hi there, how to get your code which you corrected the issues?

Green lines shows the fix red lines shows old code

**Comment by NeotenySS** [comment]
Create branch, edit code and push pull request, and author accept merge

**Comment by NeotenySS** [comment]
@Karolis-IT
