### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Saulius19** [Shadowss/TravianZ#39]
Apache` 2.4.54.2 Port 80 - PHP 7.4.33
MySQL 5.7.40 Port 3306
MariaDB 10.6.5 Port 3307
PHP 7.4.33 for CLI (Command-Line Interface)

Shadowss/TravianZ
Version 8.3.5

https://youtu.be/ghOOl7zuRA0

**Comment by Shadowss** [comment]
Video is not available
