### ISSUE TITLE
maybe this can be refactored?

### ISSUE THREAD

**Issue by 221V** [Shadowss/TravianZ#57]
hello!

question about this sh*t --

why do not scream?
https://github.com/Shadowss/TravianZ/blob/f8e3f81bba1fdd1c4712f4eb685ce84d3f0db9ff/GameEngine/Database.php#L3605-L3871

for what there needs IN(.. constructions ?
we have only single value in that field(s) --
so we can rewrite this IN(.. constructions as = only
this is the first moment

second --
we can rewrite TB_PREFIX.'fdata table from horizontal table rows like now --
to vertical table rows like
village_id + place_id + building_type + building_ lvl

and got easy select and easy update,
also store only real data -- no 0 for wasting disc/memory for no buildings on place ..

why not?

________

second question about db optimizations --
not use DELETE requsts --
replace this with UPDATE status = deleted

deleting is ok for once by daemon in week/month in night --
but not all time -- this is not best way for db perf ..

thank you :)

**Comment by 221V** [comment]
also php not search in 'strings with single quotes' variables for replace it with its values --
so 'strings with single quotes' has a bit better perf then "double quotes strings" in php ...

**Comment by 221V** [comment]
also there are prepared statement with mysqli and
PDO that can be switched from mariaDB to Postgresql
in php ..

also nice moment will be to add WebSockets ..

also we can use memcached instead current f*cking with files (locks and other, including store session's data in files)

this script needs so much work ((

**Comment by 221V** [comment]
there are no reason for that if(...) with the same sql request ...
https://github.com/Shadowss/TravianZ/blob/f8e3f81bba1fdd1c4712f4eb685ce84d3f0db9ff/Templates/Alliance/attacks.tpl#L84-L88

**Comment by Shadowss** [comment]
@221V Please can you send a pull request for akk this problem. Or a refactor for this ?

**Comment by 221V** [comment]
@Shadowss look
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16_incomming.tpl#L16-L27
1. write the same sql that repeats few times in file in line
2. there are 400 sql queries per refresh page
ahahaha
that is very funny file))
there are few times the same different sql -- that can be executed the same time, ahahaha lol))

upd. 
lol
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L225-L227

lol
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L231-L233

loool
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L259-L261

looool
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L70
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L158
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L198
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L235
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/16.tpl#L269


really funny 400 sql queries to database per page (re)load :D

**Comment by 221V** [comment]
> @221V Please can you send a pull request for akk this problem. Or a refactor for this ?

@Shadowss 
sure.
you can email me, we will discuss few moments

**Comment by Shadowss** [comment]
@221V I will send you an email.

**Comment by 221V** [comment]
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/25_4.tpl#L32-L37
maybe this can be get from db in 1-2 queries, not in 6 queries, loool

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/26_4.tpl#L33-L38

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/27_2.tpl#L49-L50

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Build/27_3.tpl#L49-L50

other question -- why there are sql queries to db in templates?
in templates must be html and data for show it only ...

**Comment by 221V** [comment]
ahaha lol
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/movement.tpl#L13-L17

looool
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/movement.tpl#L26-L31

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/movement.tpl#L65-L67

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/movement.tpl#L89-L91

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/movement.tpl#L111-L113

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/movement.tpl#L134-L135

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/movement.tpl#L154-L157

how to stop to laugh?)))

**Comment by 221V** [comment]
what
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/1.tpl#L15-L16
is
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/1.tpl#L21-L22
this
https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/1.tpl#L26-L27
?

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/3.tpl#L21-L22

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/3.tpl#L27-L28

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/3.tpl#L33-L34

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/3.tpl#L40-L41


https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/8.tpl#L13-L14

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/8.tpl#L18-L19

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/10.tpl#L12-L13

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/10.tpl#L17-L18

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/15.tpl#L14-L15

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/15.tpl#L19-L20

upd FYI -- same sql queries to db twice ...

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Notice/22.tpl#L6
this two can be rewritten to single too

**Comment by 221V** [comment]
same query many times 

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Plus/3.tpl#L3-L9

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Plus/3.tpl#L91-L92

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Plus/3.tpl#L486-L487

**Comment by 221V** [comment]
shitcode again

must not be any sql in loops

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Ajax/plusmap.tpl#L40-L42

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Ajax/plusmap.tpl#L56-L58

https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Ajax/plusmap.tpl#L145-L155


https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Ajax/mapscroll2.tpl#L111-L116


https://github.com/Shadowss/TravianZ/blob/a6eb4dd624424a32c24c797d87803ec9cfe634f3/Templates/Ajax/mapscroll.tpl#L94-L99

**Comment by 221V** [comment]
https://github.com/Shadowss/TravianZ/blob/59c1114b1c92d88b6e732cff1e8bcb372c4e3948/GameEngine/Database.php#L3739
one more "please don't scream" sql :D
