### ISSUE TITLE
Problem wdata

### ISSUE THREAD

**Issue by Zaerdin** [Shadowss/TravianZ#6]
Hello.
I have a little problem.

Error creating wdata. Check configuration or file.

Help me please.

![IMG_20191031_200645](https://user-images.githubusercontent.com/57234706/67979636-fb7bf700-fc1c-11e9-9531-1486189d68c2.jpg)

**Comment by 221V** [comment]
here that txt
https://github.com/Shadowss/TravianZ/blob/master/install/templates/wdata.tpl#L20-L22

here that get param sets
https://github.com/Shadowss/TravianZ/blob/master/install/process.php#L213

here begins populateWorldData func defined
https://github.com/Shadowss/TravianZ/blob/master/GameEngine/Database.php#L7093

here you can found few moments, when that func returns -1
https://github.com/Shadowss/TravianZ/blob/master/GameEngine/Database.php#L7111-L7121

i think that means you have problem with reading files:

or this files
https://github.com/Shadowss/TravianZ/blob/master/install/process.php#L203-L205

or this
https://github.com/Shadowss/TravianZ/blob/master/GameEngine/Database.php#L7104

so check your chmod, chown etc for that files
