### ISSUE TITLE
Map with coordinate problem

### ISSUE THREAD

**Issue by GustoVasconcelos** [Shadowss/TravianZ#74]
For **bug reports**, please use the folowing structure:

1. expected behaviour
The map should center directly on the village, but it is putting the wrong coordinates.

2. incorrect behaviour
The map has a problem with the coordinates. Once installed, it already has this bug. Could anyone test to see if it's just me that's like this?
https://github.com/user-attachments/assets/58212b26-8ada-4366-979a-45e9ca294f39

3, 4 and 5. PHP version on the server / MySQL / MariaDB version on the server
I am using docker compose for launch the server,  https://github.com/juneidy/travian-compose

**Comment by juneidy** [comment]
Duplicate. Please use the search.

https://github.com/Shadowss/TravianZ/issues/27#issuecomment-979739112

**Comment by GustoVasconcelos** [comment]
> Duplicate. Please use the search.
> 
> [#27 (comment)](https://github.com/Shadowss/TravianZ/issues/27#issuecomment-979739112)

Forgive me, I hadn't seen this problem, as it was an old problem, I didn't think it was related.
