### ISSUE TITLE
possible to run 2x travianz with the same 1x database?

### ISSUE THREAD

**Issue by peppi02** [Shadowss/TravianZ#8]
Would it be possible to run 2x travianz with the same database? For example, if you want to offer the game in 2 different languages. Or are there problems?

**Comment by 221V** [comment]
why not?
you can run at same db,
just needs different prefixes for tables

**Comment by peppi02** [comment]
With the same database I meant one and the same world. No 2 different worlds.

**Comment by 221V** [comment]
for 2 different languages just needs to add translations

**Comment by 221V** [comment]
for run 2-travianz-with-same-db-deals anyway needs to work with code a bit))

**Comment by Shadowss** [comment]
Not a issue!
