### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by WolfMaster0** [Shadowss/TravianZ#9]
when i try log in it shows this 

This page isn’t working 
worldofhackers.eu is currently unable to handle this request.
HTTP ERROR 500

please anyone help

**Comment by 221V** [comment]
what is "worldofhackers.eu" ?

**Comment by WolfMaster0** [comment]
My domain

**Comment by WolfMaster0** [comment]
My old domain so i try use it

**Comment by WolfMaster0** [comment]
And i get That error when il be home i try it other time

**Comment by 221V** [comment]
you can ask the Namecheap, your domain register company

maybe you not pay for domain?

**Comment by WolfMaster0** [comment]
I pay domain for one year

**Comment by WolfMaster0** [comment]
Now it works

**Comment by sencer07** [comment]
> Now it works

Pls help me I'm getting the same error. how did you solve
